add mp4 empty object-subrequest modifiers
AdguardTeam/tsurlfilter pull request #86
Opened 2023-06-22 17:26 UTC by Sergey-Lyapin

2023-06-22 17:33 UTC, slavaleleka commented on packages/agtree/src/compatibility-tables/modifiers/empty.yml
> +  assignable: true
`$empty` is not assignable, it is used just like that

2023-06-22 17:36 UTC, slavaleleka commented on packages/agtree/src/compatibility-tables/modifiers/mp4.yml
> +  assignable: true
also not assignable

2023-06-22 17:38 UTC, slavaleleka commented on packages/agtree/src/compatibility-tables/modifiers/mp4.yml
> +    Equivalent to $replace modifier with noopmp4-1s value.
Equivalent to **$redirect**

2023-06-22 18:41 UTC, scripthunter7 requested changes
@Sergey-Lyapin Thanks for the PR, I left some comments, please take a look

2023-06-22 18:41 UTC, scripthunter7 commented on packages/agtree/src/compatibility-tables/modifiers/empty.yml
> +  assignable: false
No need to specify, because `assignable` is `false` _by default_. Please remove this field in every case where you have set it to `false`

2023-06-22 18:41 UTC, scripthunter7 commented on packages/agtree/src/compatibility-tables/modifiers/empty.yml
> +  deprecation_message: This modifier is deprecated in favor of the $redirect modifier. Rules with $empty are converting into $redirect=nooptext now.
If you use `|-` for the `description` fields, it would make sense to use it for `deprecation_message`s as well

2023-06-22 18:41 UTC, scripthunter7 commented on packages/agtree/src/compatibility-tables/modifiers/object-subrequest.yml
> +  negatable: true
`negatable` is `true` by default, please remove this line

2023-06-23 07:37 UTC, AdamWr commented on packages/agtree/src/compatibility-tables/modifiers/empty.yml
> +    Equivalent to $replace modifier with nooptext value.
```suggestion
    Equivalent to $redirect modifier with nooptext value.
```

2023-06-23 07:37 UTC, AdamWr commented on packages/agtree/src/compatibility-tables/modifiers/empty.yml
> +    Equivalent to $replace modifier with nooptext value.
```suggestion
    Equivalent to $redirect modifier with nooptext value.
```

2023-06-23 07:37 UTC, AdamWr commented on packages/agtree/src/compatibility-tables/modifiers/empty.yml
> +    Equivalent to $replace modifier with nooptext value.
```suggestion
    Equivalent to $redirect modifier with nooptext value.
```

2023-06-23 10:29 UTC, Alex-302 requested changes

2023-06-23 10:29 UTC, Alex-302 commented on packages/agtree/src/compatibility-tables/modifiers/empty.yml
> +    Equivalent to $redirect modifier with nooptext value.
In _the table_ description is different. Table and files _must_ be synchronized.
Same for adg_ext_any and ubo_ext_any.
`200` can't be used by extensions, they use `307 redirect`

2023-06-23 11:57 UTC, slavaleleka approved these changes

2023-06-23 12:11 UTC, zloyden approved these changes

2023-06-23 12:14 UTC, AdamWr approved these changes

2023-06-23 12:32 UTC, Alex-302 approved these changes

2023-06-23 12:34 UTC, scripthunter7 approved these changes

2023-06-23 12:35 UTC, merged